<?php 
if(count($this->res) > 0){
	for($i = 0; $i < count($this->res); $i++){
?>
<div class="new_weibo">
<div class="new_weibo_user_name">
<a href="#"><img src="image/<?php echo $this->res[$i]['profile']?>"><?php echo $this->res[$i]['nickname']?></a>
</div>
<div class="new_weibo_content"> <?php echo $this->res[$i]['content']?> </div>
<?php 
if($this->res[$i]['image_url'] != Null){
?>
<div class="new_weibo_picture">
<A class="miniImg artZoom" href="image/<?php echo $this->res[$i]['image_url']?>" rel=image/a01.jpg><IMG class="small" src="image/<?php echo $this->res[$i]['image_url']?>"></A>
</div>
<?php 
}
?>
<div class="weibo_info">
<div class="date_time">
<a href="#"><?php echo $this->res[$i]['create_time']?></a>
</div>
<div class="from_address"> 来自网站 </div>

<div class="comment_and_retransmission">
<a href="#">赞</a> | <a href="#">转发</a> | <a href="#">收藏</a> | <span id="comment"
	cursor="pointer">评论</span>
	
</div>



<!-- 
这里是评论开始
-->
<?php if($i == 0){?>
<div id="msgBox">
<form>
<h2>发表评论</h2>
<div>
<input id="userName" class="f-text" value="shiqiang" type="hidden"/>
<p id="face"><img src="/image/shiqiang_pinglun.png" class="current" /></p>
</div>
<div><input id="conBox" class="f-text"></div>
<div class="tr">
<p>
<span class="countTxt">还能输入</span><strong class="maxNum">140</strong><span>个字</span>
<input id="sendBtn" type="button" value="发 表" title="快捷键 Ctrl+Enter" />
</p>
</div>
</form>
<div class="list">
<h3><span>所有评论</span></h3>
<ul>

</ul>
</div>
</div>
<?php }?>
<!-- 
这里是评论结束
-->


</div>
</div>
<?php 
	}
}
?>