<div id="msgBox">
<form>
<h2>发表评论</h2>
<div>
<input id="userName" class="f-text" value="shiqiang" type="hidden"/>
<p id="face"><img src="" class="current" /></p>
</div>
<div><input id="conBox" class="f-text"></div>
<div class="tr">
<p>
<span class="countTxt">还能输入</span><strong class="maxNum">140</strong><span>个字</span>
<input id="sendBtn" type="button" value="发 表" title="快捷键 Ctrl+Enter" />
</p>
</div>
</form>
<div class="list">
<h3><span>所有评论</span></h3>
<ul>

</ul>
</div>
</div>