<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<link type="image/x-icon" rel="shortcut icon" href="<?php echo $this->baseUrl;?>/image/index/favicon.ico" />

<link rel="stylesheet" type="text/css" href="/css/utils/window.css">
<link rel="stylesheet" type="text/css" href="/css/index.css">
<link rel="stylesheet" type="text/css" href="/css/utils/weiboContent.css">
<link rel="stylesheet" type="text/css" href="/css/utils/header.css">
<link rel="stylesheet" type="text/css" href="/css/utils/mainRight.css">
<link rel="stylesheet" type="text/css" href="/css/utils/sendWeibo.css">
<link rel="stylesheet" type="text/css" href="/css/utils/footer.css">

<script type="text/javascript" src="/js/utils/jquery-2.1.3.js"></script>
<script type="text/javascript" src="/js/utils/JSDump.js"></script>
<script type="text/javascript" src="/js/utils/showOneWeibo.js"></script>
<script type="text/javascript" src="/js/index.js"></script>
<script type="text/javascript" src="/js/utils/header.js"></script>
<script type="text/javascript" src="/js/utils/mainRight.js"></script>
<script type="text/javascript" src="/js/utils/weiboContent.js"></script>
<script type="text/javascript" src="/js/plupload/plupload.full.min.js"></script>
<script type="text/javascript" src="/js/utils/sendWeibo.js"></script>
</head>
<body>
<?php
	require_once APPLICATION_PATH . '/views/scripts/utils/header.phtml';
?>
<div class="main_wrap" id="main_wrap">
<div class="main_left" id="main_left">

<?php 
	require_once APPLICATION_PATH . '/views/scripts/utils/sendWeibo.phtml';
?>

<div class="top_tab">
<div class="tab_item_active">
<a href="#">我关注的</a>
</div>
<div class="tab_item_not_active">
<a href="#">实时推荐</a>
</div>
<div class="tab_item_not_active">
<a href="#">朋友圈</a>
</div>
</div>

<?php 
	require_once APPLICATION_PATH . '/views/scripts/utils/weiboContent.phtml';
?>
</div>

<?php 
	require_once APPLICATION_PATH . '/views/scripts/utils/mainRight.phtml';
?>
<div class="clear"></div>
</div>
<?php 
	require_once APPLICATION_PATH . '/views/scripts/utils/footer.phtml';
?>
</body>
</html>
