<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title>thinksns</title> <link href="image/favicon.ico"
	type="image/x-cion" rel="shortcut icon">
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl;?>/css/index.css">
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl;?>/css/artZoom.css">

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl;?>/css/send_message.css">


<script type="text/javascript" src="/js/jquery-1.3.2.min.js"></script> 

<script type="text/javascript" src="/js/index.js"></script>



<script type="text/javascript" src="/js/send_message.js"></script>


<script type="text/javascript" src="/js/artZoom.js"></script>

<script type="text/javascript">jQuery('a.artZoom').artZoom();</script>

<script type="text/javascript" src="/js/scrollpagination.js"></script>
<script type="text/javascript">

$(document).ready(function(){
	  $("#comment").click(function(){
		$("#msgBox").toggle();
	  });
	});

$(document).ready(function(){
	  $("#send_weibo_button").click(function(){
		  $.get("/index/index", function(){
		  var d = new Date();
		  var temp='<div class="new_weibo"><div class="new_weibo_user_name"><a href="#"><img src="image/shiqiang.jpg">shiqiang</a>'
			+ '</div>'
			+ '<div class="new_weibo_content"> ' + $("#send_weibo_textarea").val() + ' </div>'
			+ '<div class="weibo_info">'
			+ '<div class="date_time">'
			+ '<a href="#">' + d + '</a>'
			+ '</div>'
			+ '<div class="from_address"> 来自网站 </div>'
			+ '<div class="comment_and_retransmission">'
			+ '<a href="#">赞</a> | <a href="#">转发</a> | <a href="#">收藏</a> | <span id="comment"'
			+ 'cursor="pointer">评论</span></div>';
		$("#content").prepend(temp);
		$("#send_weibo_textarea").val("");
		  });
	  });
	});


	$(document).ready(function(){
		  $("#main_right_intersting_people_follow_button").click(function(){
			  $.get("/index/jiaguanzhu", function(){
				  $("#main_right_intersting_people_follow_button").html("取消关注");
			  });
		  });
		});



</script>

</head>
<body>
<div id="header">
<div class="header_content">
<div class="header_nav">
<a href="#"> <img src="/image/home_header_logo.png" alt="logo" />
</a>
<ul>
<li onmouseover="header_nav_hover(this)"
	onmouseout="header_nav_out(this)" class="header_current_page"> <a
	href="#" target="_self">首页</a></li>
<li onmouseover="show_apps_list(this)" onmouseout="hide_apps_list(this)"
	id="apps"><a href="#" target="_self">热门</a> <div
	class="header_apps_list" id="header_apps_list">
<div class="app_link">
<a href="#"> <img src="/image/app01.png" alt="app1" /> 群组
</a>
</div>
<div class="app_link">
<a href="#"> <img src="/image/app01.png" alt="app1" /> 更多应用
</a>
</div>
</div></li>
<li onmouseover="show_apps_list(this)" onmouseout="hide_apps_list(this)"
	id="apps"><a href="#" target="_self">应用</a> <div
	class="header_apps_list" id="header_apps_list">
<div class="app_link">
<a href="#"> <img src="/image/app01.png" alt="app1" /> 群组
</a>
</div>
<div class="app_link">
<a href="#"> <img src="/image/app01.png" alt="app1" /> 更多应用
</a>
</div>
</div></li>
<li onmouseover="show_apps_list(this)" onmouseout="hide_apps_list(this)"
	id="apps"><a href="#" target="_self">游戏</a> <div
	class="header_apps_list" id="header_apps_list">
<div class="app_link">
<a href="#"> <img src="/image/app01.png" alt="app1" /> 群组
</a>
</div>
<div class="app_link">
<a href="#"> <img src="/image/app01.png" alt="app1" /> 更多应用
</a>
</div>
</div></li>
</ul>

</div>
<div class="header_right">
<div class="header_search">
<input class="search_text" type="text" value="搜微博 / 昵称 / 标签"
	onfocus="this.value = ''" onblur="this.value = '搜微博 / 昵称 / 标签'" /> <a href="/index/sousuo" target="_blank"><input
	class="search_button" type="image" src="/image/home_header_search.png"
	alt="submit"></a>

</div>
<ul>
<li onmouseover="header_nav_hover(this)"
	onmouseout="header_nav_out(this)"><a href="#" target="_self"><?php echo $_GET['nickname']?></a></li>
<li onmouseover="show_message_list(this)"
	onmouseout="hide_message_list(this)" id="message"><a href="#"
	target="_self">消息</a>
<div class="header_message_list" id="header_message_list">
<div class="header_list_a_line">
<a href="#"> @提到我的 </a>
</div>

</div></li>
<li onmouseover="header_nav_hover(this)"
	onmouseout="header_nav_out(this)"><a href="#" target="_self">设置</a></li>
</ul>
</div>
</div>
</div>
<div class="main_wrap" id="main_wrap">
<div class="main_left" id="main_left">
<div class="top_tab">
<div class="tab_item_active">
<a href="#">搜索结果</a>
</div>
</div>
<div class="content" id="content">
<?php 
if(count($this->res) > 0){
	for($i = 0; $i < count($this->res); $i++){
?>
<div class="new_weibo">
<div class="new_weibo_user_name">
<a href="#"><img src="/image/<?php echo $this->res[$i]['profile']?>"><?php echo $this->res[$i]['nickname']?></a>
</div>
<div class="new_weibo_content"> <?php echo $this->res[$i]['content']?> </div>
<?php 
if($this->res[$i]['image_url'] != Null){
?>
<div class="new_weibo_picture">
<A class="miniImg artZoom" href="/image/<?php echo $this->res[$i]['image_url']?>" rel=image/a01.jpg><IMG class="small" src="/image/<?php echo $this->res[$i]['image_url']?>"></A>
</div>
<?php 
}
?>
<div class="weibo_info">
<div class="date_time">
<a href="#"><?php echo $this->res[$i]['create_time']?></a>
</div>
<div class="from_address"> 来自网站 </div>

<div class="comment_and_retransmission">
<a href="#">赞</a> | <a href="#">转发</a> | <a href="#">收藏</a> | <span id="comment"
	cursor="pointer">评论</span>
	
</div>



<!-- 
这里是评论开始
-->
<?php if($i == 0){?>
<div id="msgBox">
<form>
<h2>发表评论</h2>
<div>
<input id="userName" class="f-text" value="shiqiang" type="hidden"/>
<p id="face"><img src="/image/shiqiang_pinglun.png" class="current" /></p>
</div>
<div><input id="conBox" class="f-text"></div>
<div class="tr">
<p>
<span class="countTxt">还能输入</span><strong class="maxNum">140</strong><span>个字</span>
<input id="sendBtn" type="button" value="发 表" title="快捷键 Ctrl+Enter" />
</p>
</div>
</form>
<div class="list">
<h3><span>所有评论</span></h3>
<ul>

</ul>
</div>
</div>
<?php }?>
<!-- 
这里是评论结束
-->


</div>
</div>
<?php 
	}
}
?>
</div>