<div id="footer">
<div class="footer_item">
<div class="footer_item_topic"> 手机玩微博 </div>
<div class="footer_item_link_item">
<a href="#">Android客户端</a>
</div>
<div class="footer_item_link_item">
<a href="#">iPhone客户端</a>
</div>
</div>
<div class="footer_item">
<div class="footer_item_topic"> 开发者中心 </div>
<div class="footer_item_link_item">
<a href="#">开发者认证</a>
</div>
<div class="footer_item_link_item">
<a href="#">开发者文档</a>
</div>
</div>
<div class="footer_item">
<div class="footer_item_topic"> 意见和交流 </div>
<div class="footer_item_link_item">
<a href="#">问题反馈</a>
</div>
<div class="footer_item_link_item">
<a href="#">联系客服</a>
</div>
</div>
<div class="footer_item">
<div class="footer_item_topic"> 关于我们 </div>
<div class="footer_item_link_item">
<a href="#">公司介绍</a>
</div>
<div class="footer_item_link_item">
<a href="#">加入我们</a>
</div>
</div>
<div class="copy_right_info">
<div class="copy_right_info_left"> &copy2012ZHishiSoft All Rights
Reserved. </div>
<div class="copy_right_info_right"> Powered By ThinkSNS </div>
</div>
</div>