<div class="send_weibo_tips_top">
<div class="send_weibo_tips_top_left"> 分享是一种态度~ </div>
<div class="send_weibo_tips_top_right">
可以输入<span class="send_weibo_tips_top_right_num">140</span>个字
</div>
</div>

<textarea class="send_weibo_textarea" id="send_weibo_textarea" name="send_weibo_textarea"></textarea>
<div class="send_weibo_with_super_function">

	<div class="superFunctionItem">
		<a class="super_function_type" href="#" onclick="super_function_type_onclick(this)"> <img
		src="<?php echo $this->baseUrl;?>/image/index/super_function_type_01.png" /> 表情
		</a>

		<div class="send_weibo_with_super_function_hidden_panel">
			<div class="send_weibo_with_super_function_hidden_panel_arrow">
				<img src="<?php echo $this->baseUrl;?>/image/index/send_weibo_with_super_function_hidden_panel_arrow.png"/>
			</div>
			<div class="send_weibo_with_super_function_hidden_panel_wrap">
				<div class="send_weibo_with_super_function_hidden_panel_toplabel">
					<span class="send_weibo_with_super_function_hidden_panel_toplabel_text">常用表情</span>
					<span><a class="send_weibo_with_super_function_hidden_panel_close" href="#" onclick="send_weibo_with_super_function_hidden_panel_close_onclick(this)"><img src="<?php echo $this->baseUrl;?>/image/index/send_weibo_with_super_function_hidden_panel_toplabel_close.png"></a></span>
				</div>
				<div class="send_weibo_with_super_function_hidden_panel_itemlist">
					<?php 
						$files = array_diff(scandir(APPLICATION_PATH . '/../public/image/emotion'), array('.', '..'));
						foreach ($files as $key => $value) {
					?>
					<a href="javascript:void(0)" onclick="emoOnclick(this)"><div class="emoItem" onmouseenter="emoItemOnmouseenter(this)" onmouseleave="emoItemOnmouseleave(this)"><img name="<?php echo substr($value, 0, strlen($value) - 4);?>" src="/image/emotion/<?php echo $value?>"><div class="emoHint"><?php echo substr($value, 0, strlen($value) - 4)?></div></div></a>
					<?php 
						}
					?>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>

	<div class="superFunctionItem">
		<a class="super_function_type" href="#" onclick="super_function_type_onclick(this)"> <img
		src="<?php echo $this->baseUrl;?>/image/index/supFunType02.png" /> 图片
		</a>
	
		<div class="send_weibo_with_super_function_hidden_panel">
			<div class="send_weibo_with_super_function_hidden_panel_arrow">
				<img src="<?php echo $this->baseUrl;?>/image/index/send_weibo_with_super_function_hidden_panel_arrow.png"/>
			</div>
			<div class="send_weibo_with_super_function_hidden_panel_wrap">
				<div class="send_weibo_with_super_function_hidden_panel_toplabel">
					<span class="send_weibo_with_super_function_hidden_panel_toplabel_text">共 0 张，还能上传 9 张</span>
					<span><a class="send_weibo_with_super_function_hidden_panel_close" href="#" onclick="send_weibo_with_super_function_hidden_panel_close_onclick(this)"><img src="<?php echo $this->baseUrl;?>/image/index/send_weibo_with_super_function_hidden_panel_toplabel_close.png"></a></span>
				</div>
				<div class="send_weibo_with_super_function_hidden_panel_itemlist">

					<div class="send_weibo_with_super_function_hidden_panel_item" id="addImg">
						<a href="javascript:void(0);">
							<div id="send_weibo_with_super_function_hidden_panel_item_add_image">
								<img src="<?php echo $this->baseUrl;?>/image/index/send_weibo_with_super_function_hidden_panel_item_add_image.png"/>
							</div>
						</a>
					</div>

					<div class="clear"></div>

				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>

	<input type="image" src="<?php echo $this->baseUrl;?>/image/index/send_weibo_button.png" id="send_weibo_button" />

</div>