<!DOCTYPE html>
<html>
<head>
	<title>testphp</title>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="./index.css"/>
	<script type="text/javascript" src="./index.js"></script>
</head>
<body>
	<div id="infoWrap">
		<a href="#"><div id="profile"><img src="/image/user_profile/shiqiang.jpg"/></div></a>
		<div id="basicInfo">
			<div id="infoLeft">
				<a href="#"><div id="nickName">seeker</div></a>
				<div id="genderAndAddr">
					<img src="/image/maleIcon.png">
					<span id="addr">北京市 北京市 海淀区</span>
				</div>
				<div id="intro">个人简介:我喜欢的一句话就能说清楚的产品</div>
				<div id="friendOperation">
					<a href="#"><div id="following">已关注</div></a>
					<a href="#"><div id="sendPriMes">发私信</div></a>
					<a href="#"><div id="more">更多</div></a>
				</div>
			</div>
			<div id="infoRight">
				<div>
					<div class="main_right_link_info">
					<div class="main_right_link_info_item"
						onmouseover="link_info_item_mouse_over(this)"
						onmouseout="link_info_item_mouse_out(this)">
					<a href="/index/myweibo" target="_blank">微博<br />
					</a>
					</div>
					<div class="main_right_link_info_item"
						onmouseover="link_info_item_mouse_over(this)"
						onmouseout="link_info_item_mouse_out(this)">
					<a href="/index/my_following_user" target="_blank">关注<br />
					</a>
					</div>
					<div class="main_right_link_info_item main_right_link_info_item_last"
						onmouseover="link_info_item_mouse_over(this)"
						onmouseout="link_info_item_mouse_out(this)">
					<a href="/index/follow_me_user" target="_blank">粉丝<br />
					</a>
					</div>
					</div>
				</div>
			</div>
		</div>
		<div id="clear"></div>
	</div>
</body>
</html>