<html>
<head>
	<title>Login</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="/css/utils/window.css">
	<link rel="stylesheet" href="/css/login.css">
	<script type="text/javascript" src="/js/utils/jquery-2.1.3.js"></script>
	<script type="text/javascript" src="/js/utils/jquery.cookie.js"></script>
	<script type="text/javascript" src="/js/login.js"></script>
</head>
<body>
	<div id="top_content_wrap">
		<div id="login_logo_1">ThinkSNS</div>
		<div id="login_logo_2">选择T3,选择不平凡！</div>
		<form action="/login/login" method="post" id="loginForm">
		<div id="login_basic_form">
			<input type="text" id="user_name_input" name="logName"/>
			<input type="password" id="user_password_input" name="password"/>
			<input type="image" src="/image/login/login_button_image.png" id="login_submit_button"/>
			<input id="rememberedPw" type="hidden"  name="rememberedPw" value="0"/>
		</div>
		<div id="login_addition_option">
			<div id="keep_login_and_login_info">
				<input type="checkbox" id="keep_login_checkbox" name="keep_login" value="1"/>记住密码
				<span id="login_info">
					<?php
						echo $this->loginInfo;
					?>
				</span>
			</div>
			<div id="forget_password_and_sign_up">
    			<a href="/login/showforget" id="forget_password">忘记密码?</a>
    			<a href="/login/showregister" id="sign_up">注册</a>
    		</div>
		</div>
		</form>
	</div>
</body>
</html>